# Generated by Django 5.0.7 on 2024-08-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
